<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BanksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('banks')->insert([
            [
                'bank_code' => '001',
                'bank_name' => 'Bank Indonesia',
                'bank_image' => 'bank_indonesia.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '002',
                'bank_name' => 'Bank Rakyat Indonesia (BRI)',
                'bank_image' => 'bri.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '008',
                'bank_name' => 'Bank Mandiri',
                'bank_image' => 'mandiri.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '009',
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'bank_image' => 'bni.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '014',
                'bank_name' => 'Bank Central Asia (BCA)',
                'bank_image' => 'bca.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '451',
                'bank_name' => 'Bank Syariah Indonesia (BSI)',
                'bank_image' => 'bsi.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '013',
                'bank_name' => 'Bank Permata',
                'bank_image' => 'permatabank.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '022',
                'bank_name' => 'CIMB Niaga',
                'bank_image' => 'cimb_niaga.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '028',
                'bank_name' => 'Bank OCBC NISP',
                'bank_image' => 'ocbc_nisp.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '026',
                'bank_name' => 'Bank Panin',
                'bank_image' => 'paninbank.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '045',
                'bank_name' => 'Bank BTPN',
                'bank_image' => 'btpn.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '153',
                'bank_name' => 'Bank Sinarmas',
                'bank_image' => 'sinarmas.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '054',
                'bank_name' => 'Bank Maybank Indonesia',
                'bank_image' => 'maybank.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '011',
                'bank_name' => 'Bank Danamon',
                'bank_image' => 'danamon.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '152',
                'bank_name' => 'Bank Commonwealth',
                'bank_image' => 'commonwealth.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '950',
                'bank_name' => 'Bank Jago',
                'bank_image' => 'jago.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '028',
                'bank_name' => 'Bank Mega',
                'bank_image' => 'mega.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '089',
                'bank_name' => 'Bank Muamalat Indonesia',
                'bank_image' => 'muamalat.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '427',
                'bank_name' => 'Bank Tabungan Negara (BTN)',
                'bank_image' => 'btn.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => '114',
                'bank_name' => 'Bank Panin Dubai Syariah',
                'bank_image' => 'panin_syariah.png',
                'bank_type' => 'bank',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // E-Wallet
            [
                'bank_code' => 'ew001',
                'bank_name' => 'GoPay',
                'bank_image' => 'gopay.png',
                'bank_type' => 'ewallet',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => 'ew002',
                'bank_name' => 'OVO',
                'bank_image' => 'ovo.png',
                'bank_type' => 'ewallet',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => 'ew003',
                'bank_name' => 'DANA',
                'bank_image' => 'dana.png',
                'bank_type' => 'ewallet',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => 'ew004',
                'bank_name' => 'LinkAja',
                'bank_image' => 'linkaja.png',
                'bank_type' => 'ewallet',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => 'ew005',
                'bank_name' => 'ShopeePay',
                'bank_image' => 'shopeepay.png',
                'bank_type' => 'ewallet',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => 'ew006',
                'bank_name' => 'Jenius Pay',
                'bank_image' => 'jenius.png',
                'bank_type' => 'ewallet',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => 'ew007',
                'bank_name' => 'i.Saku',
                'bank_image' => 'isaku.png',
                'bank_type' => 'ewallet',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => 'ew008',
                'bank_name' => 'DOKU',
                'bank_image' => 'doku.png',
                'bank_type' => 'ewallet',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => 'ew009',
                'bank_name' => 'Sakuku',
                'bank_image' => 'sakuku.png',
                'bank_type' => 'ewallet',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => 'ew010',
                'bank_name' => 'JakOne Mobile',
                'bank_image' => 'jakone.png',
                'bank_type' => 'ewallet',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => 'ew011',
                'bank_name' => 'OCTO Mobile',
                'bank_image' => 'octo_mobile.png',
                'bank_type' => 'ewallet',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => 'ew012',
                'bank_name' => 'Paytren',
                'bank_image' => 'paytren.png',
                'bank_type' => 'ewallet',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => 'ew013',
                'bank_name' => 'SPIN Pay',
                'bank_image' => 'spinpay.png',
                'bank_type' => 'ewallet',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => 'ew014',
                'bank_name' => 'BluePay',
                'bank_image' => 'bluepay.png',
                'bank_type' => 'ewallet',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_code' => 'ew015',
                'bank_name' => 'Yap!',
                'bank_image' => 'yap.png',
                'bank_type' => 'ewallet',
                'bank_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
